#!/bin/bash
# sets the backlight to the percent value of first argument.
# Deprecated should just get xbacklight to work
# watch out as this has no sanity checks while directly writing to /sys
old=$(cat /sys/class/backlight/intel_backlight/brightness)
max=$(cat /sys/class/backlight/intel_backlight/max_brightness)
new=$((max * $1 / 100))
echo $new > /sys/class/backlight/intel_backlight/brightness
